name: groci
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  velocity_x:
    git:
      url: https://github.com/chihuy105/VelocityX.git
      ref: stable
  google_fonts: ^6.2.1
  line_icons: 2.0.3
  flutter_form_builder: ^9.5.0
  getwidget: 5.0.0
  counter_button: 1.0.1
  get_storage: 2.1.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  icons_launcher: ^3.0.0
  lottie: ^3.3.0
  cached_network_image: ^3.4.1
  stylish_bottom_bar:
  simple_barcode_scanner:
  liquid_pull_to_refresh:
  animate_do:
  logger: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons:
  change_app_package_name:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true
